base_dir: "./example"
whisper_models_dir: "./whisper.cpp/models"
model_names:
  - "ggml-base.en"
  # - "ggml-small.en"
  # - "ggml-large"
use_preconverted: false  # set to true to use pre-converted files
preconverted_dir: "./example/wav_temp"  # directory containing pre-converted files
other_params: "-pc -mc 0"